### PR TITLE
Don’t convert SVG viewBox attribute to lowercase

### PR DESCRIPTION
**Pull request by arturi**
Because it’s case-sensitive, and Bel doesn’t correct it, please see https://github.com/shama/bel/wiki#svg and https://github.com/shama/bel/issues/45

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Thanks for the PR! All SVG attributes are case sensitive, so perhaps we should just preserve case by default, and not do `propName.toLowerCase()` [on line 154](https://github.com/arturi/babel-plugin-yo-yoify/blob/3e30b01f23977d5de1604c412a59a9681dc7c675/index.js#L154). Then we don't need to special-case any SVG attributes. That's what `bel` normally does too so it would be more consistent. Can you change it to do that?

**Comment by arturi** [comment]
> perhaps we should just preserve case by default

Yes, I tried that first, but it failed, and I thought its was a bad idea, but the reason it failed was because there is `classname` to `clas`s conversion on [line 155](https://github.com/arturi/babel-plugin-yo-yoify/blob/3e30b01f23977d5de1604c412a59a9681dc7c675/index.js#L155), which expected `classname` to be lowercased. I changed it to `className`.

**Comment by goto-bus-stop** [comment]
:100:, thanks! Released as v0.3.1!

**Comment by arturi** [comment]
Thank you!

**Pull request merged**
